// crossfire_christmas resorce list

// Lines marked with "//" are default and listed for reference

//decals.wad
//gfx/env/nightbk.tga
//gfx/env/nightdn.tga
//gfx/env/nightft.tga
//gfx/env/nightlf.tga
//gfx/env/nightrt.tga
//gfx/env/nightup.tga
//halflife.wad
models/xfirexmasmdl/present1.mdl
models/xfirexmasmdl/present2.mdl
models/xfirexmasmdl/present_bluewhite.mdl
models/xfirexmasmdl/present_medium.mdl
models/xfirexmasmdl/xmasratsmall.mdl
overviews/crossfire_christmas.bmp
overviews/crossfire_christmas.tga
overviews/crossfire_christmas.txt
sound/xfirexmassnd/3dm_bik_ball.wav
sound/xfirexmassnd/hos.wav
sound/xfirexmassnd/jbloop.wav
sound/xfirexmassnd/predictingsnow.wav
sound/xfirexmassnd/santahohoho.wav
//sprites/glow01.spr
sprites/xfirexmasspr/rotflakebs.SPR
sprites/xfirexmasspr/snow.spr
//maps/chrossfire_christmas.map
maps/chrossfire_christmas.res
maps/chrossfire_christmas.txt

models/player/cs1.0_arctic/cs1.0_arctic.mdl
models/player/cs1.0_gign/cs1.0_gign.mdl
models/player/cs1.0_gsg9/cs1.0_gsg9.mdl
models/player/cs1.0_guerilla/cs1.0_guerilla.mdl
models/player/cs1.0_leet/cs1.0_leet.mdl
models/player/cs1.0_sas/cs1.0_sas.mdl
models/player/cs1.0_terror/cs1.0_terror.mdl
models/player/cs1.0_urban/cs1.0_urban.mdl
models/player/cs1.0_vip/cs1.0_vip.mdl
models/player/dod_allie-heavy/dod_allie-heavy.mdl
models/player/dod_allie-light/dod_allie-light.mdl
models/player/dod_allie-medium/dod_allie-medium.mdl
models/player/dod_allie-mg/dod_allie-mg.mdl
models/player/dod_allie-para/dod_allie-para.mdl
models/player/dod_allie-sniper/dod_allie-sniper.mdl
models/player/dod_axis-heavy/dod_axis-heavy.mdl
models/player/dod_axis-inf/dod_axis-inf.mdl
models/player/dod_axis-light/dod_axis-light.mdl
models/player/dod_axis-medium/dod_axis-medium.mdl
models/player/dod_axis-mg/dod_axis-mg.mdl
models/player/dod_axis-para/dod_axis-para.mdl
models/player/dod_axis-sniper/dod_axis-sniper.mdl
models/player/dod_brit-inf/dod_brit-inf.mdl
models/player/dod_us-inf/dod_us-inf.mdl
models/player/ricochet_female/ricochet_female.mdl
models/player/ricochet_male/ricochet_male.mdl
models/player/cs1.0_arctic/cs1.0_arctic.bmp
models/player/cs1.0_gign/cs1.0_gign.bmp
models/player/cs1.0_gsg9/cs1.0_gsg9.bmp
models/player/cs1.0_guerilla/cs1.0_guerilla.bmp
models/player/cs1.0_leet/cs1.0_leet.bmp
models/player/cs1.0_sas/cs1.0_sas.bmp
models/player/cs1.0_terror/cs1.0_terror.bmp
models/player/cs1.0_urban/cs1.0_urban.bmp
models/player/cs1.0_vip/cs1.0_vip.bmp
models/player/dod_allie-heavy/dod_allie-heavy.bmp
models/player/dod_allie-light/dod_allie-light.bmp
models/player/dod_allie-medium/dod_allie-medium.bmp
models/player/dod_allie-mg/dod_allie-mg.bmp
models/player/dod_allie-para/dod_allie-para.bmp
models/player/dod_allie-sniper/dod_allie-sniper.bmp
models/player/dod_axis-heavy/dod_axis-heavy.bmp
models/player/dod_axis-inf/dod_axis-inf.bmp
models/player/dod_axis-light/dod_axis-light.bmp
models/player/dod_axis-medium/dod_axis-medium.bmp
models/player/dod_axis-mg/dod_axis-mg.bmp
models/player/dod_axis-para/dod_axis-para.bmp
models/player/dod_axis-sniper/dod_axis-sniper.bmp
models/player/dod_brit-inf/dod_brit-inf.bmp
models/player/dod_us-inf/dod_us-inf.bmp
models/player/ricochet_female/ricochet_female.bmp
models/player/ricochet_male/ricochet_male.bmp