// ps2waypoint.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (9):
decals.wad
gbx1.wad
gfx/env/nightbk.tga
gfx/env/nightdn.tga
gfx/env/nightft.tga
gfx/env/nightlf.tga
gfx/env/nightrt.tga
gfx/env/nightup.tga
hlps2.wad

models/player/civilian_tf2c/civilian_tf2c.mdl
models/player/mercenary/mercenary.mdl
models/player/TFcivilian/TFcivilian.mdl
models/player/TFdemo/TFdemo.mdl
models/player/TFdemo2/TFdemo2.mdl
models/player/TFengineer/TFengineer.mdl
models/player/TFengineer2/TFengineer2.mdl
models/player/TFhvyweapon/TFhvyweapon.mdl
models/player/TFhvyweapon2/TFhvyweapon2.mdl
models/player/TFmedic/TFmedic.mdl
models/player/TFMedic2/TFmedic2.mdl
models/player/TFpyro/TFpyro.mdl
models/player/TFpyro2/TFpyro2.mdl
models/player/TFscout/TFscout.mdl
models/player/TFscout2/TFscout2.mdl
models/player/TFsniper/TFsniper.mdl
models/player/TFsniper2/TFsniper2.mdl
models/player/TFsoldier/TFsoldier.mdl
models/player/TFsoldier2/TFsoldier2.mdl
models/player/TFspy/TFspy.mdl
models/player/TFspy2/TFspy2.mdl
models/player/TFcivilian/TFcivilian.bmp
models/player/TFdemo/TFdemo.bmp
models/player/TFdemo2/TFdemo2.bmp
models/player/TFengineer/TFengineer.bmp
models/player/TFengineer2/TFengineer2.bmp
models/player/TFhvyweapon/TFhvyweapon.bmp
models/player/TFhvyweapon2/TFhvyweapon2.bmp
models/player/TFmedic/TFmedic.bmp
models/player/TFMedic2/TFmedic2.bmp
models/player/TFpyro/TFpyro.bmp
models/player/TFpyro2/TFpyro2.bmp
models/player/TFscout/TFscout.bmp
models/player/TFscout2/TFscout2.bmp
models/player/TFsniper/TFsniper.bmp
models/player/TFsniper2/TFsniper2.bmp
models/player/TFsoldier/TFsoldier.bmp
models/player/TFsoldier2/TFsoldier2.bmp
models/player/TFspy/TFspy.bmp
models/player/TFspy2/TFspy2.bmp
models/player/dm_colette/dm_colette.mdl
models/player/dm_colette/dm_colette.bmp
models/player/dm_gina/dm_gina.mdl
models/player/dm_gina/dm_gina.bmp
models/player/skeleton/skeleton.bmp
models/player/skeleton/skeleton.mdl
models/player/blue/blue.bmp
models/player/blue/blue.mdl
models/player/red/red.bmp
models/player/red/red.mdl
models/player/civilian_tf2c/civilian_tf2c.mdl
models/player/mercenary/mercenary.mdl
models/player/TFcivilian/TFcivilian.mdl
models/player/TFdemo/TFdemo.mdl
models/player/TFdemo2/TFdemo2.mdl
models/player/TFengineer/TFengineer.mdl
models/player/TFengineer2/TFengineer2.mdl
models/player/TFhvyweapon/TFhvyweapon.mdl
models/player/TFhvyweapon2/TFhvyweapon2.mdl
models/player/TFmedic/TFmedic.mdl
models/player/TFMedic2/TFmedic2.mdl
models/player/TFpyro/TFpyro.mdl
models/player/TFpyro2/TFpyro2.mdl
models/player/TFscout/TFscout.mdl
models/player/TFscout2/TFscout2.mdl
models/player/TFsniper/TFsniper.mdl
models/player/TFsniper2/TFsniper2.mdl
models/player/TFsoldier/TFsoldier.mdl
models/player/TFsoldier2/TFsoldier2.mdl
models/player/TFspy/TFspy.mdl
models/player/TFspy2/TFspy2.mdl
models/player/TFcivilian/TFcivilian.bmp
models/player/TFdemo/TFdemo.bmp
models/player/TFdemo2/TFdemo2.bmp
models/player/TFengineer/TFengineer.bmp
models/player/TFengineer2/TFengineer2.bmp
models/player/TFhvyweapon/TFhvyweapon.bmp
models/player/TFhvyweapon2/TFhvyweapon2.bmp
models/player/TFmedic/TFmedic.bmp
models/player/TFMedic2/TFmedic2.bmp
models/player/TFpyro/TFpyro.bmp
models/player/TFpyro2/TFpyro2.bmp
models/player/TFscout/TFscout.bmp
models/player/TFscout2/TFscout2.bmp
models/player/TFsniper/TFsniper.bmp
models/player/TFsniper2/TFsniper2.bmp
models/player/TFsoldier/TFsoldier.bmp
models/player/TFsoldier2/TFsoldier2.bmp
models/player/TFspy/TFspy.bmp
models/player/TFspy2/TFspy2.bmp
models/player/dm_colette/dm_colette.mdl
models/player/dm_colette/dm_colette.bmp
models/player/dm_gina/dm_gina.mdl
models/player/dm_gina/dm_gina.bmp
models/player/skeleton/skeleton.bmp
models/player/skeleton/skeleton.mdl
models/player/blue/blue.bmp
models/player/blue/blue.mdl
models/player/red/red.bmp
models/player/red/red.mdl
models/player/cannibal/Cannibal.bmp
models/player/cannibal/cannibal.mdl
models/player/ken/ken.bmp
models/player/ken/ken.mdl
models/player/botnes/botnes.mdl
models/player/botnes/botnes.bmp
models/player/cs1.0_arctic/cs1.0_arctic.mdl
models/player/cs1.0_gign/cs1.0_gign.mdl
models/player/cs1.0_gsg9/cs1.0_gsg9.mdl
models/player/cs1.0_guerilla/cs1.0_guerilla.mdl
models/player/cs1.0_leet/cs1.0_leet.mdl
models/player/cs1.0_sas/cs1.0_sas.mdl
models/player/cs1.0_terror/cs1.0_terror.mdl
models/player/cs1.0_urban/cs1.0_urban.mdl
models/player/cs1.0_vip/cs1.0_vip.mdl
models/player/dod_allie-heavy/dod_allie-heavy.mdl
models/player/dod_allie-light/dod_allie-light.mdl
models/player/dod_allie-medium/dod_allie-medium.mdl
models/player/dod_allie-mg/dod_allie-mg.mdl
models/player/dod_allie-para/dod_allie-para.mdl
models/player/dod_allie-sniper/dod_allie-sniper.mdl
models/player/dod_axis-heavy/dod_axis-heavy.mdl
models/player/dod_axis-inf/dod_axis-inf.mdl
models/player/dod_axis-light/dod_axis-light.mdl
models/player/dod_axis-medium/dod_axis-medium.mdl
models/player/dod_axis-mg/dod_axis-mg.mdl
models/player/dod_axis-para/dod_axis-para.mdl
models/player/dod_axis-sniper/dod_axis-sniper.mdl
models/player/dod_brit-inf/dod_brit-inf.mdl
models/player/dod_us-inf/dod_us-inf.mdl
models/player/ricochet_female/ricochet_female.mdl
models/player/ricochet_male/ricochet_male.mdl
models/player/cs1.0_arctic/cs1.0_arctic.bmp
models/player/cs1.0_gign/cs1.0_gign.bmp
models/player/cs1.0_gsg9/cs1.0_gsg9.bmp
models/player/cs1.0_guerilla/cs1.0_guerilla.bmp
models/player/cs1.0_leet/cs1.0_leet.bmp
models/player/cs1.0_sas/cs1.0_sas.bmp
models/player/cs1.0_terror/cs1.0_terror.bmp
models/player/cs1.0_urban/cs1.0_urban.bmp
models/player/cs1.0_vip/cs1.0_vip.bmp
models/player/dod_allie-heavy/dod_allie-heavy.bmp
models/player/dod_allie-light/dod_allie-light.bmp
models/player/dod_allie-medium/dod_allie-medium.bmp
models/player/dod_allie-mg/dod_allie-mg.bmp
models/player/dod_allie-para/dod_allie-para.bmp
models/player/dod_allie-sniper/dod_allie-sniper.bmp
models/player/dod_axis-heavy/dod_axis-heavy.bmp
models/player/dod_axis-inf/dod_axis-inf.bmp
models/player/dod_axis-light/dod_axis-light.bmp
models/player/dod_axis-medium/dod_axis-medium.bmp
models/player/dod_axis-mg/dod_axis-mg.bmp
models/player/dod_axis-para/dod_axis-para.bmp
models/player/dod_axis-sniper/dod_axis-sniper.bmp
models/player/dod_brit-inf/dod_brit-inf.bmp
models/player/dod_us-inf/dod_us-inf.bmp
models/player/ricochet_female/ricochet_female.bmp
models/player/ricochet_male/ricochet_male.bmp